license: xxxx-xxxx-xxxx-xxxx
mysql:
  host: localhost
  port: 3306
  database: miraclepvp
  username: username
  password: password
discord:
  link: 'https://discord.gg/TPXdxJK'
lobby:
  location: new;0.0;0.0;0.0;0.0;0.0;
sign:
  reloaddelay: 300
broadcast:
  servername: KitPvP
  delay: 900
  messages:
    - 'Set endless messages <3 in the config'
    - '&d&m-----------------------------------------------------<br>&f%server_name%<br> <br>&7Test message<br>&d&m-----------------------------------------------------'
chat:
  curseWords:
    - cancer
    - aids
    - cunt
    - stupid
    - fuck
    - fucking
    - fucked
    - arsehole
    - assshole
    - assface
    - asshat
    - asswipe
    - fuckbutt
    - fuckhead
    - gayass
    - shitspitter
    - butt
    - ass-hat
    - assbag
    - assbite
    - asscock
    - asshead
    - asslick
    - assmonkey
    - assmunch
    - assshit
    - asssucker
    - bampot
    - bitchass
    - clitface
    - cockbite
    - cockburger
    - cockface
    - cockfucker
    - cockhead
    - cockmonkey
    - cocknose
    - cocknugget
    - cockshit
    - cockwaffle
    - cumbubble
    - cumtart
    - cuntass
    - cuntface
    - cuntrag
    - cuntslut
    - dickbag
    - dickface
    - dickfuck
    - dickwad
    - dickweasel
    - dickweed
    - dickwod
    - dipshit
    - doochbag
    - douche-fag
    - dumass
    - dumbfuck
    - dumbass
    - dumbshit
    - dumshit
    - fuckass
    - fuckbag
    - fuckboy
    - fuckbrain
    - fuckersucker
    - fuckface
    - fucknut
    - fucknutt
    - fucktart
    - fuckup
    - fuckwad
    - fuckwitt
    - homodumbshit
    - jackass
    - jagoff
    - jerkass
    - peckerhead
    - puto
    - shitass
    - shitbag
    - shitbagger
    - shitbrains
    - shitcunt
    - shitdick
    - shithole
    - suckass
    - thundercunt
    - twatlips
    - whorebag
    - whoreface
    - idiot
    - homosexual
    - unclefucker
    - twatwaffle
    - queerhole
    - queerbait
    - queer
    - polesmoker
    - penispuffer
    - penisfucker
    - penisbanger
    - muffdiver
    - mcfagget
    - lezzie
    - lesbo
    - lesbian
    - homo
    - gaywad
    - gaytard
    - gaylord
    - gayfuckist
    - gayfuck
    - gaydo
    - gaybob
    - gay
    - fudgepacker
    - flamer
    - faggotcock
    - faggot
    - faggit
    - fagfucker
    - fagbag
    - fag
    - dyke
    - douchewaffle
    - dike
    - dicktickler
    - dicksucker
    - dickmonger
    - dickfucker
    - cuntlicker
    - cumjockey
    - cumguzzler
    - cocksucker
    - cocksniffer
    - cocksmoker
    - cocksmoke
    - cocksmith
    - cockmuncher
    - cockmongruel
    - cockmongler
    - cockmaster
    - cockknoker
    - cockjockey
    - carpetmuncher
    - buttfucker
    - buttfucka
    - butt-pirate
    - bumblefuck
    - brotherfucker
    - bitchtits
    - asspirate
    - asspirate
    - asshopper
    - assgoblin
    - assfucker
    - assbanger
    - assbandit
    - ass-pirate
    - ass-jabber
    - asses
    - assfuck
    - butts
    - assfuck
    - asshole
    - asslicker
    - assnigger
    - axwound
    - cameltoe
    - coochie
    - coochy
    - cunnie
    - cunthole
    - gooch
    - kooch
    - kootch
    - kunt
    - minge
    - muff
    - pissflaps
    - poonani
    - poontang
    - punanny
    - snatch
    - vagina
    - vajayjay
    - vjayjay
    - bastard
    - beaner
    - wetback
    - bitch
    - punta
    - bitches
    - bitchy
    - blowjob
    - clitfuck
    - cunnilingus
    - dickslap
    - dicksucking
    - fellatio
    - feltch
    - fuckin
    - fucks
    - handjob
    - humping
    - munging
    - pussylicking
    - skullfuck
    - titfuck
    - tittyfuck
    - wank
    - wankjob
    - wanker
    - boner
    - renob
    - bullshit
    - smeg
    - douchebag
    - fagtard
    - fatass
    - fuckbutter
    - fucked
    - fucker
    - fucking
    - fuckoff
    - fucktard
    - fuckwit
    - goddamn
    - goddamnit
    - gringo
    - guido
    - heeb
    - kike
    - hell
    - honkey
    - lameass
    - lardass
    - mothafuckin
    - motherfucker
    - motherfucking
    - niggers
    - niglet
    - paki
    - pecker
    - pussies
    - pussy
    - rimjob
    - ruski
    - sand nigger
    - sandnigger
    - shitface
    - shitfaced
    - shithouse
    - shitter
    - shittiest
    - shitting
    - shitty
    - slut
    - slutbag
    - tard
    - retard
    - tit
    - tits
    - whore

